name: CI

on:
  - push
  - pull_request

env:
  DEFAULT_PYTHON: "3.11"

jobs:
  black:
    name: Check Black
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip --version

      - name: Install Black
        run: |
          pip install black

      - name: Run Black
        run: |
          black --check --diff aemet_opendata

      - name: Run Black on examples
        run: |
          black --check --diff examples

  pylint:
    name: Check Pylint (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip --version

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Install Pylint
        run: |
          pip install pylint

      - name: Run Pylint
        run: |
          pylint aemet_opendata

      - name: Install aemet_opendata
        run: |
          pip install --upgrade .

      - name: Run Pylint on examples
        run: |
          pylint examples

  mypy:
    name: Check Mypy (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip --version

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Install Mypy
        run: |
          pip install mypy

      - name: Run Mypy
        run: |
          mypy --strict aemet_opendata

      - name: Install aemet_opendata
        run: |
          pip install --upgrade .

      - name: Run Mypy on examples
        run: |
          mypy --check-untyped-defs examples

  ruff:
    name: Check ruff
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip --version

      - name: Install ruff
        run: |
          pip install ruff

      - name: Run ruff
        run: |
          ruff check aemet_opendata

      - name: Run ruff on examples
        run: |
          ruff check examples
