name: CI

on:
  - push
  - pull_request

env:
  DEFAULT_PYTHON: "3.11"

jobs:
  black:
    name: Check Black
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip --version

      - name: Install Black
        run: |
          pip install black

      - name: Run Black
        run: |
          black --check --diff aemet_opendata

  pylint:
    name: Check Pylint (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip --version

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: Install Pylint
        run: |
          pip install pylint

      - name: Run Pylint
        run: |
          pylint aemet_opendata

  ruff:
    name: Check ruff
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          pip --version

      - name: Install ruff
        run: |
          pip install ruff

      - name: Run ruff
        run: |
          ruff check aemet_opendata
